include:
  - board: seeeduino_xiao_ble
    shield: totem_left_dongle prospector_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right_dongle prospector_adapter
# there is no settingsreset (needed) for the XIAO
