include:
  - board: seeeduino_xiao_ble
    shield: totem_left prospector_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right prospector_adapter
# there is no settingsreset (needed) for the XIAO
